/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { HttpContext, HttpHeaders } from "@angular/common/http";
/** Request payload for updating user profile information. */
export interface UserUpdate {
    /** Updated first name. */
    firstName?: string;
    /** Updated last name. */
    lastName?: string;
    /** Updated email address. Must be unique. */
    email?: string;
}

/** User profile data returned by the API. */
export interface UserDTO {
    /** Unique user identifier. */
    id?: string | null;
    /** First name. */
    firstName?: string;
    /** Last name. */
    lastName?: string;
    /** Email address. */
    email?: string;
}

export interface ProblemDetail {
    type?: string;
    title?: string;
    status?: number;
    detail?: string;
    instance?: string;
    properties?: Record<string, any>;
}

/** Request payload for creating or updating a mail. */
export interface MailRequest {
    /** Mail subject. Between 1 and 20 characters. */
    subject?: string;
    /** Mail body. Between 1 and 500 characters. */
    content?: string;
    /** UUIDs of internal TO recipients. */
    toIds?: Array<string>;
    /** UUIDs of internal CC recipients. */
    ccIds?: Array<string>;
    /** UUIDs of internal BCC recipients. */
    bccIds?: Array<string>;
    /** UUIDs of internal Reply-To recipients. */
    replyToIds?: Array<string>;
    /** Optional external email address for SMTP delivery. */
    externalRecipientAddress?: string | null;
}

/** Metadata for an uploaded file attachment. */
export interface AttachmentDTO {
    /** File size in bytes. */
    size?: number;
    /** Original filename. */
    fileName?: string | null;
    /** MIME type of the file. */
    mimeType?: string | null;
    /** Server-side path used to retrieve the file via the /images endpoint. */
    path?: string;
}

/** Mail data returned by the API. */
export interface MailDTO {
    /** Unique mail identifier. */
    id?: string | null;
    /** The user who created and sent this mail. */
    sender?: UserDTO;
    /** Mail subject. */
    subject?: string;
    /** Mail body text. */
    content?: string;
    /** Current status of the mail (CREATED, SENT, RECEIVED). */
    status?: 'DRAFT' | 'SENT' | 'RECEIVED' | 'ERROR';
    /** Origin of the mail (INTERNAL or EXTERNAL). */
    source?: 'EXTERN' | 'INTERN';
    /** TO recipients. */
    to?: Array<UserDTO>;
    /** CC recipients. */
    cc?: Array<UserDTO>;
    /** BCC recipients. */
    bcc?: Array<UserDTO>;
    /** Reply-To recipients. */
    replyTo?: Array<UserDTO>;
    /** Optional external SMTP recipient address. */
    externalRecipientAddress?: string | null;
    /** Uploaded file attachments. */
    attachments?: Array<AttachmentDTO>;
    /** Support ticket number, present on incoming external mails. */
    ticketNumber?: string | null;
    /** Timestamp when the mail was created. */
    createdAt?: Date;
    /** Timestamp of the last update. */
    updatedAt?: Date;
    /** Timestamp when the mail was sent. Null for drafts. */
    sentAt?: string | null;
}

/** Request payload for replying to an incoming support mail. */
export interface SupportReplyRequest {
    /** Reply text. Between 1 and 500 characters. */
    content?: string;
}

export interface ExternalMailDTO {
    id?: string;
    folder?: string;
    subject?: string;
    from?: string;
    to?: Array<string>;
    cc?: Array<string>;
    replyTo?: Array<string>;
    content?: string;
    attachmentNames?: Array<string>;
    receivedAt?: string | null;
    sentAt?: string | null;
}

/** Request Options for Angular HttpClient requests */
export interface RequestOptions<TResponseType extends 'arraybuffer' | 'blob' | 'json' | 'text'> {
    headers?: HttpHeaders;
    reportProgress?: boolean;
    responseType?: TResponseType;
    withCredentials?: boolean;
    context?: HttpContext;
}
