/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Mail controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, MailDTO, MailRequest, SupportReplyRequest } from "../models";

@Injectable({ providedIn: "root" })
export class MailService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    getMailById(mailId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<MailDTO>;
    getMailById(mailId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<MailDTO>>;
    getMailById(mailId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<MailDTO>>;
    /** Returns a single mail by ID. The caller must be the sender, a recipient, or it must be a shared support mail. */
    getMailById(mailId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/mails/${mailId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    updateDraft(mailId: string, data: MailRequest, attachments: Array<Blob>, observe?: 'body', options?: RequestOptions<'json'>): Observable<MailDTO>;
    updateDraft(mailId: string, data: MailRequest, attachments: Array<Blob>, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<MailDTO>>;
    updateDraft(mailId: string, data: MailRequest, attachments: Array<Blob>, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<MailDTO>>;
    /** Updates an existing draft mail. Only the sender may update their own drafts. Sent mails cannot be modified. */
    updateDraft(mailId: string, data: MailRequest, attachments: Array<Blob>, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/mails/${mailId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Remove Content-Type for multipart (browser will set it with boundary)
        headers = headers.delete('Content-Type');

        const formData = new FormData();
        if (data !== undefined) {
            formData.append('data', String(data));
        }
        if (attachments !== undefined && Array.isArray(attachments)) {
            attachments.forEach((item) => {
                if (item !== undefined && item !== null) {
                    formData.append('attachments', item);
                }
            });
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, formData, requestOptions);
    }

    deleteMail(mailId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    deleteMail(mailId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    deleteMail(mailId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    /** Permanently deletes a mail. Only the sender may delete their own mails. */
    deleteMail(mailId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/mails/${mailId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }

    createDraft(data: MailRequest, attachments: Array<Blob>, observe?: 'body', options?: RequestOptions<'json'>): Observable<MailDTO>;
    createDraft(data: MailRequest, attachments: Array<Blob>, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<MailDTO>>;
    createDraft(data: MailRequest, attachments: Array<Blob>, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<MailDTO>>;
    /** Creates a new draft mail with optional file attachments. */
    createDraft(data: MailRequest, attachments: Array<Blob>, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/mails`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Remove Content-Type for multipart (browser will set it with boundary)
        headers = headers.delete('Content-Type');

        const formData = new FormData();
        if (data !== undefined) {
            formData.append('data', String(data));
        }
        if (attachments !== undefined && Array.isArray(attachments)) {
            attachments.forEach((item) => {
                if (item !== undefined && item !== null) {
                    formData.append('attachments', item);
                }
            });
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, formData, requestOptions);
    }

    replyToSupportMail(mailId: string, data: SupportReplyRequest, attachments: Array<Blob>, observe?: 'body', options?: RequestOptions<'json'>): Observable<MailDTO>;
    replyToSupportMail(mailId: string, data: SupportReplyRequest, attachments: Array<Blob>, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<MailDTO>>;
    replyToSupportMail(mailId: string, data: SupportReplyRequest, attachments: Array<Blob>, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<MailDTO>>;
    /** Creates and sends a reply to an incoming support mail. The reply subject includes the original ticket number. */
    replyToSupportMail(mailId: string, data: SupportReplyRequest, attachments: Array<Blob>, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/mails/${mailId}/reply`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Remove Content-Type for multipart (browser will set it with boundary)
        headers = headers.delete('Content-Type');

        const formData = new FormData();
        if (data !== undefined) {
            formData.append('data', String(data));
        }
        if (attachments !== undefined && Array.isArray(attachments)) {
            attachments.forEach((item) => {
                if (item !== undefined && item !== null) {
                    formData.append('attachments', item);
                }
            });
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, formData, requestOptions);
    }

    createAndSendMail(requestBody?: Record<string, any>, observe?: 'body', options?: RequestOptions<'json'>): Observable<MailDTO>;
    createAndSendMail(requestBody?: Record<string, any>, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<MailDTO>>;
    createAndSendMail(requestBody?: Record<string, any>, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<MailDTO>>;
    /** Creates a new mail and immediately sends it without saving a draft first. */
    createAndSendMail(requestBody?: Record<string, any>, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/mails/send`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, requestBody, requestOptions);
    }

    sendMail(mailId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    sendMail(mailId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    sendMail(mailId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    /** Sends a previously created draft mail by its ID. */
    sendMail(mailId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/mails/send/${mailId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, null, requestOptions);
    }

    getSentMails(observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<MailDTO>>;
    getSentMails(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<MailDTO>>>;
    getSentMails(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<MailDTO>>>;
    /** Returns all mails sent by the authenticated user. */
    getSentMails(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/mails/sent`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    getInbox(observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<MailDTO>>;
    getInbox(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<MailDTO>>>;
    getInbox(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<MailDTO>>>;
    /** Returns all incoming mails for the authenticated user, including shared support mails. */
    getInbox(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/mails/incoming`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    getDrafts(observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<MailDTO>>;
    getDrafts(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<MailDTO>>>;
    getDrafts(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<MailDTO>>>;
    /** Returns all draft mails created by the authenticated user. */
    getDrafts(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/mails/drafts`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }
}
