/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for MailGateway controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, ExternalMailDTO } from "../models";

@Injectable({ providedIn: "root" })
export class MailGatewayService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    getIncomingExternalMail(limit?: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<ExternalMailDTO>>;
    getIncomingExternalMail(limit?: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<ExternalMailDTO>>>;
    getIncomingExternalMail(limit?: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<ExternalMailDTO>>>;
    /** Returns the most recent messages from the configured IMAP mailbox. Requires IMAP gateway to be enabled. */
    getIncomingExternalMail(limit?: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/mail-gateway/incoming`;

        let params = new HttpParams();
        if (limit != null) {
            params = HttpParamsBuilder.addToHttpParams(params, limit, 'limit');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }
}
