server {
    listen ${PORT};
    server_name ${SERVER_NAME};
    return 301 https://$host$request_uri;
}

server {
    listen ${SSL_PORT} ssl;
    server_name ${SERVER_NAME};

    ssl_certificate     ${SSL_CERT_FILE};
    ssl_certificate_key ${SSL_CERT_KEY_FILE};

    server_tokens off;

    proxy_set_header Host              $host;
    proxy_set_header X-Real-IP         $remote_addr;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    location = / {
        return 301 /app/;
    }

    location /app/ {
        proxy_pass http://mailclient:80/app/;
    }

    location /api/ {
        proxy_pass http://mailserver:8080/api/;
    }

    location = /healthz {
        access_log off;
        modsecurity off;
        return 200 "healthy\n";
    }
}
